### ISSUE TITLE
improvement: show the domain name in the end results

### ISSUE THREAD

**Issue by royharoush** [inquisb/keimpx#20]
Hi, 
today keimpx only shows the username\hash\password combination. 
during red team engagement we do alot of domain-user-hash\password rotation, and though the end output today is useful, it still requires to QA the result becaue it doesnt show with what domain (when domains are specified from a file), was used in a successful login. 
thanks,
Roy

**Comment by NEXUS2345** [comment]
Hi Roy,

This was added in #23.

Thanks,
NEXUS2345
